# Generated by Django 3.2.9 on 2021-11-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='имя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название')),
                ('imdb_rating', models.FloatField(verbose_name='оценка')),
                ('genre', models.CharField(choices=[('unknown', 'не определен'), ('anime', 'аниме'), ('bio', 'биографический'), ('action', 'боевик'), ('western', 'вестерн'), ('military', 'военный'), ('detective', 'детектив'), ('children', 'детский'), ('documentary', 'документальный'), ('drama', 'драма'), ('historical', 'исторический'), ('comedy', 'комедия'), ('concert', 'концерт'), ('short', 'короткометражный'), ('criminal', 'криминал'), ('melodrama', 'мелодрама'), ('mystic', 'мистика'), ('music', 'музыка'), ('cartoon', 'мультфильм'), ('musical', 'мюзикл'), ('scientific', 'научный'), ('adventure', 'приключения'), ('reality', 'реалити - шоу'), ('family', 'семейный'), ('sport', 'спорт'), ('horrors', 'ужасы'), ('fantastic', 'фантастика')], default='unknown', max_length=50, verbose_name='жанр')),
                ('description', models.TextField(verbose_name='описание')),
                ('writers_names', models.TextField(blank=True, verbose_name='имена сценаристов')),
                ('director', models.TextField(verbose_name='директор фильма')),
                ('actors_names', models.TextField(blank=True, verbose_name='имена актеров')),
                ('actors', models.ManyToManyField(related_name='movies_for_actors', to='moviesLibrary.Actor')),
                ('writers', models.ManyToManyField(related_name='movies_for_writer', to='moviesLibrary.Writer')),
            ],
        ),
    ]
